// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA7styGO0cPPEPuawwRz3qxDQDv7oxcCM',
    appId: '1:1069425920284:web:d5932100621678bbf312d9',
    messagingSenderId: '1069425920284',
    projectId: 'app-for-baduk-robot-5vzlm0',
    authDomain: 'app-for-baduk-robot-5vzlm0.firebaseapp.com',
    databaseURL: 'https://app-for-baduk-robot-5vzlm0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-for-baduk-robot-5vzlm0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqO85pYv2U_s2Ycg_-wOdNmGkFsu3Vvo',
    appId: '1:1069425920284:android:52028432ae495a31f312d9',
    messagingSenderId: '1069425920284',
    projectId: 'app-for-baduk-robot-5vzlm0',
    databaseURL: 'https://app-for-baduk-robot-5vzlm0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-for-baduk-robot-5vzlm0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSpZJYTHpWeWMao-pDmpezbRoS8jvz-w',
    appId: '1:1069425920284:ios:a111e95c1d4a4205f312d9',
    messagingSenderId: '1069425920284',
    projectId: 'app-for-baduk-robot-5vzlm0',
    databaseURL: 'https://app-for-baduk-robot-5vzlm0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-for-baduk-robot-5vzlm0.appspot.com',
    iosBundleId: 'com.example.badukApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFSpZJYTHpWeWMao-pDmpezbRoS8jvz-w',
    appId: '1:1069425920284:ios:87377a1ec06af340f312d9',
    messagingSenderId: '1069425920284',
    projectId: 'app-for-baduk-robot-5vzlm0',
    databaseURL: 'https://app-for-baduk-robot-5vzlm0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-for-baduk-robot-5vzlm0.appspot.com',
    iosBundleId: 'com.example.badukApp.RunnerTests',
  );
}
